### ISSUE TITLE
Hi jrmarino again, about Linux

### ISSUE THREAD

**Issue by hoper-a11y** [jrmarino/ravensw#3]
Again, please pardon me if this is the wrong place for that.

I don't know if you tested your bootstrap on distros other than mainstream distros (CentOS or Ubuntu) but I'm using a minor distro and I'm having problems with raven on this distro. Yes, I could switch to the mainstream, but this would make raven less universal.

I have used both FreeBSD and Linux and sorry if it upset you since you are also on the FreeBSD foundation, I have to said that FreeBSD's pkg is not a good utility and I'm 100% agree with you when you want to rewrite it in Ada. Even on FreeBSD, I usually got pkg segfault. It's much worse on Linux.

Linux's glibc is not good for static linking at all. glibc's version incompatibility is a real problem. I used to got pkg to segfault a lot on my Linux system and I found that it can't handle big package (like LLVM Clang). It failed at verifying checksum. If I install the downloaded package manually by pkg, it worked fine. Sometimes, it's very slow to fetch packages. I checked and found it's not about my network connection but it seemed pkg can't spawn new threads or processes or something like that, since I'm not a programmer I don't know but it seemed to be the case after I checked it with top and various task manager (xfce's task manager, mate's system monitor...). pkg just sat there and did nothing, the system is mostly idle. I found if I caught into this situation the only way to escape is restart the whole system and run pkg again, this time it happily downloading the package with very good speed but after one or two other packages it slowed again and I have to reboot again. Sometimes, waiting for it to install a package was too long so I have to cancel it with Ctrl+C.

I think you should consider allowing us to build the bootstrap pack from source instead of using your prebuilt bootstrap. Currently I didn't found any instruction for that. This would eliminate the problem with glibc and after that if pkg is still segfault, that's definitely it own problem.

I know why you don't do that currently. It's about to save time and since raven was written in Ada instead of a normal C/C++ build environment, we also have to setup an Ada build environment. But it's not really a problem. The Ada stuffs most of the time already packaged by distros. You only have to write an instruction about which packages to be installed to have a complete Ada build environment and then here we go, it's pretty much straight forward.

Sorry about my wall of text and please let me know what you think.

**Comment by kraileth** [comment]
Regarding pkg(8): John designed RP to be package manager agnostic. However an initial package manager was needed and since his primary platform is DragonFly he modified pkg to use Zstandard compression and used that (the permissive licensing is probably a bonus, too). Investigating dpkg, rpm and so on later, they were disregarded because they are in fact much worse. Still probably nobody would stop you if you decided that you like e.g. dpkg (which we already package) better and either write a tool to convert the pkg-style meta data to that required by dpkg or to contribute code that would enable ravenadm to write DEB packages.

The segfaults are not only occurring on your distro, they unfortunately happen on Linux in general all the time. A couple of attempts were made to fix the issues that plague especially the Linux version (involving a fork called "ravensw") - and while some problems were identified and fixed, it seems that there are still some more remaining... Eventually it was decided to bite the bullet and kind of re-implement pkg in Ada.

On Linux your best bet right now is to use `pkg add` instead of `pkg install`. That seems to work reliably. However I agree that this is a pretty bad situation right now rendering RP almost useless on Linux for the time being.

Just curious: Which Linux distro are you on? I have a soft spot in my heart for some of the underdogs which actually do really well but nevertheless stay niche. E.g. I hope that we'll support Linux/Musl someday.

There actually are some notes that can help it bringing up Raven on a platform for which no boostrap package exists, yet. But it's not very easy to do (plus some of the info is obsolete by now). My plan was to do a full platform-bringup on CentOS 6 so that we can also support distros with really old glibc. Also I wanted to add FreeBSD-i386 and an illumos distro. Since doing it all by hand over and over again might not be a good idea, I started writing a tool that is meant to assist with the bring-up: https://github.com/kraileth/miniraven. It's not done, yet, and after the decision to move to an Ada-based ravensw I put things on hold for now. But I intend to finish it when the new ravensw is available.

Oh, and in case you're missing some packages that are not yet available in RP, feel free to edit the wishlist and request new ports: https://github.com/jrmarino/Ravenports/wiki/Wishlist (as you can see we're not exactly running out of requests, but quite some were already accomplished so far).

Hopefully the situation in Linux land will improve really soon.

**Comment by hoper-a11y** [comment]
Not really an underdog. I'm using Sparky Linux MATE Edition. It's really a minor distro but it's based on Debian, a giant, but not really widely used in commercial as CentOS and Ubuntu. They use stock Debian + their own artwork and utilities, so if it failed on Sparky, it also failed on vanilla Debian.

**Comment by hoper-a11y** [comment]
pkg is a very bad tool. I setup a clean and minimal debian system from netinstall iso and tried to set other thing up using raven. It again failed at checking integrity...malloc(): unsorted double linked list corrupted. I again think the problem is with the prebuilt binary and glibc. Please give me instruction how to build the bootstrap from source so I could test if the pkg build with native libc6 also fail or not.

**Comment by hoper-a11y** [comment]
OK here we go again. I installed DragonflyBSD on my spare SSD. The plain old pkg caused my system to hang when installing libreoffice. I have to cold reset my system. After that, I tried to install libreoffice again, it said libreoffice is not installed (luckily!) and let me install it again. Everything this time work as expected. I think it could be not pkg's fault. It could be because Hammer2 turn deduplication on by default and this system only has 8G of ram that caused the system to hang.

**Comment by jrmarino** [comment]
@hoper-a11y 
Make sure you're using ravensw with the version ending in "_6".  One of our users tracked down the major issue with package conflict resolution and it affected ALL platforms.  Since that fix, ravensw is much more stable on DragonFly and FreeBSD.  Linux is still a disaster.  We haven't even published the fix for solaris yet (I only cycle back to it every few weeks because it shares hardware with freebsd).

**Comment by jrmarino** [comment]
I probable should rebuild the bootstraps with the latest pkg ...

**Comment by hoper-a11y** [comment]
> I probable should rebuild the bootstraps with the latest pkg ...

Please doing so.

Today I revisit your quick start wiki for Linux, that same wiki dated back to 2018. The bootstrap archive is still the same, with our plain old pkg and pkg-static.

I notice something very strange: I ran pkg (the dynamic linked version, isn't it?) but it output error related to pkg-static:

pkg-static: failed to find the version elf note

That dynamic linked pkg failed with:

Checking integrity...Child process pid=2312 terminated abnormally: Segmentation fault.

Then I tried to use pkg-static, it successfully let me installed wget-complete-standard but this same pkg-static failed to install gcc9-complete-standard with:

Checking integrity...malloc(): unsorted double linked list corrupted
Child process pid=2350 terminated abnormally: Aborted

As you can see: all of the symptom point out to problem with libc. So I asked you to build your bootstrap on a Debian Buster system and check if they still fail with the same errors.

**Comment by hoper-a11y** [comment]
When will you update the bootstrap for SunOS and Linux? I'm still waiting.

**Comment by jrmarino** [comment]
it's been hectic.  you don't need to wait for me.  pkg-static can install the latest ravensw from packages.  In fact, that's what is supposed to happened - but it doesn't when the packages have different names.
Any way, hopefully soon.

**Comment by hoper-a11y** [comment]
> it's been hectic. you don't need to wait for me. pkg-static can install the latest ravensw from packages. In fact, that's what is supposed to happened - but it doesn't when the packages have different names.
> Any way, hopefully soon.

Why don't you let me know sooner? I installed ravensw this way and copied and renamed everything pkg related in /raven/etc and it worked. It's more stable than pkg, but still bad. The same old checking integrity and segmentation fault. You know, I'm already lost my patient with that pkg sh*t on Linux so I would better close this issue since I no longer have any interests on that pkg sh*t on Linux. I will focus on Illumos, though, I'm not yet given up on ravenports yet :smile:

**Comment by jrmarino** [comment]
on linux?  Yes, we told you it segfaults on linux.  It always has.
But I do need to repackage the bootstrap.  And double check that glibc is dynamically linked.  It may not be.  let's leave this open.

**Comment by hoper-a11y** [comment]
> on linux? Yes, we told you it segfaults on linux. It always has.
> But I do need to repackage the bootstrap. And double check that glibc is dynamically linked. It may not be. let's leave this open.

I still keep Linux VMs to test when you have your new bootstrap updated. But I admit I don't expect much. I will focus on Illumos, though.

**Comment by jrmarino** [comment]
The linux issues were resolved a while ago.
